fixing the command

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -29,17 +29,18 @@ phases:
       - echo Updating ECS Task Definition...
 
       - TASK_DEF=$(aws ecs describe-task-definition --task-definition $ECS_TASK_DEFINITION)
+
       - NEW_TASK_DEF=$(echo $TASK_DEF | jq --arg IMAGE "$ECR_URI/$ECR_REPOSITORY:$CODEBUILD_RESOLVED_SOURCE_VERSION" '.taskDefinition | .containerDefinitions[0].image=$IMAGE | del(.taskDefinitionArn,.revision,.status,.requiresAttributes,.compatibilities,.registeredAt,.registeredBy)')
 
       - echo "$NEW_TASK_DEF" > new-task-def.json
 
       - TASK_REVISION=$(aws ecs register-task-definition --cli-input-json file://new-task-def.json --query 'taskDefinition.taskDefinitionArn' --output text)
 
-      - echo "Running ECS task..."
+      - echo Running ECS task...
 
       - TASK_ARN=$(aws ecs run-task --cluster $ECS_CLUSTER --launch-type FARGATE --task-definition $TASK_REVISION --query 'tasks[0].taskArn' --output text)
 
-      - echo "Waiting for task to stop..."
+      - echo Waiting for task to stop...
 
       - aws ecs wait tasks-stopped --cluster $ECS_CLUSTER --tasks $TASK_ARN
 
@@ -47,8 +48,4 @@ phases:
 
       - echo "Exit Code: $EXIT_CODE"
 
-      - |
-        if [ "$EXIT_CODE" != "0" ]; then
-          echo "ECS Tests Failed"
-          exit 1
-        fi
+      - if [ "$EXIT_CODE" != "0" ]; then echo "ECS Tests Failed"; exit 1; fi
