fixing indentation

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -52,10 +52,8 @@ phases:
 
       - echo "Exit Code: $EXIT_CODE"
 
-      - echo "Exit Code: $EXIT_CODE"
-
       - |
-         if [ "$EXIT_CODE" != "0" ]; then
-         echo "ECS Tests Failed"
-         exit 1
-         fi
+        if [ "$EXIT_CODE" != "0" ]; then
+          echo "ECS Tests Failed"
+          exit 1
+        fi
