fixing the failure command

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -52,4 +52,10 @@ phases:
 
       - echo "Exit Code: $EXIT_CODE"
 
-      - if [ "$EXIT_CODE" != "0" ]; then exit 1; fi
+      - echo "Exit Code: $EXIT_CODE"
+
+      - |
+         if [ "$EXIT_CODE" != "0" ]; then
+         echo "ECS Tests Failed"
+         exit 1
+         fi
